# 127.0.0.1 redirected to posts.com in etc/hosts file
@url = https://ticketing.com

# get all orders
GET {{url}}/api/orders
Content-Type: application/json
###


# create a order
POST {{url}}/api/orders
Content-Type: application/json

{
  "ticketId": "6165f78400ffe062521e60f6"
}
###


# get one
GET {{url}}/api/orders/6165f78f3e62887242bcf41d
Content-Type: application/json
###


# delete a ticket
DELETE {{url}}/api/orders/6165f78f3e62887242bcf41d
Content-Type: application/json
###