# 127.0.0.1 redirected to posts.com in etc/hosts file
@url = https://ticketing.com

# get all orders
GET {{url}}/api/orders
Content-Type: application/json
###


# create a order
POST {{url}}/api/orders
Content-Type: application/json

{
  "ticketId": "6165d5bcd9d8b0bfcb69dd97"
}
###


# get one
GET {{url}}/api/orders/616589e76f970eef787becf8
Content-Type: application/json
###


# delete a ticket
DELETE {{url}}/api/orders/616589726f970eef787bece6
Content-Type: application/json
###