# 127.0.0.1 redirected to posts.com in etc/hosts file
@url = https://ticketing.com


# create a payment
POST {{url}}/api/payments
Content-Type: application/json

{
  "token": "tok_visa",
  "orderId": "6165f99a3e62887242bcf437"
}
###

